### ISSUE TITLE
It may need a global agent

### ISSUE THREAD

**Issue by evanlong0803** [SchnapsterDog/nuxt-chatgpt#11]

**Comment by dosstx** [comment]
I agree.

We need to establish some context for the bot. We need a `system` role so we can keep the bot between its bounds (guardrails) and then a `user` and `assistant` role to help fine-tune the responses.

See this for an example: https://github.com/vueschool/ai-chatbot-course/blob/boilerplate/agents/customerSupportAgent.ts

**Comment by SchnapsterDog** [comment]
@dosstx Now this is available through `chatCompletion` function.
