### ISSUE TITLE
Why the apiKey not stored in runtimeConfig object?

### ISSUE THREAD

**Issue by dosstx** [SchnapsterDog/nuxt-chatgpt#14]
The docs state:
```
// entirely optional
  chatgpt: {
    apiKey: 'Your apiKey here goes here'
  },
```

Wouldn't you want to reference the key within the `runtimeConfig` property like so?

```
	runtimeConfig: {
		OPENAI_API_KEY: "" //<---- would be copied form an `.env` file
	},
```

**Comment by SchnapsterDog** [comment]
@dosstx You can do like this:

chatgpt: {
    apiKey: 'Here to bind the runtimeConfig Key'
  },
