### ISSUE TITLE
Im getting 500 (Internal Server Error) 

### ISSUE THREAD

**Issue by vickykeen** [SchnapsterDog/nuxt-chatgpt#17]
Im not sure why iam getting this error do i need to pay or the free trial can be used?

**Comment by wokalek** [comment]
Same. But I tried to see what code I recived and this is `429 - Rate limit reached for requests`.
Don't know how to use this without a paid plan.

**Comment by zhaolinlau** [comment]
same here

**Comment by SchnapsterDog** [comment]
This is related to openai API.
