### ISSUE TITLE
Prompt not properly parsed in the endpoint

### ISSUE THREAD

**Issue by AbdelH2O** [SchnapsterDog/nuxt-chatgpt#8]
## Expected Behavior
- A response related to the prompt the user provides.

## Actual Behavior
- A totally random response.

## Steps to Reproduce the Problem

  Basically use the library by making a simple request according to their example.

## Specifications

  - Version: 0.1.8
  - Platform: MacOS
  - Subsystem: Unix

**Comment by SchnapsterDog** [comment]
@AbdelH2O Thanks mate for catching and fixing this. PR Approved merged to master branch.
